import {
  MdWifi,
  MdBolt,
  MdLocalGasStation,
  MdDelete,
  MdWaterDrop,
  MdTv,
  MdSecurity,
  MdCleaningServices,
  MdLocalParking,
  MdBuild,
  MdBed,
  MdApartment,
  MdKingBed,
  MdWeekend,
  MdVilla,
  MdHome,
  MdHomeWork,
  MdHolidayVillage,
  MdDomain,
  MdStairs,
  MdSingleBed,
  MdBedroomParent,
  MdHotel,
  MdHotelClass,
  MdStar,
  MdFamilyRestroom,
  MdBusiness,
  MdCorporateFare,
  MdGroups,
  MdStorefront,
  MdWarehouse,
  MdLan,
  MdPerson,
  MdBalcony,
  MdDeck,
  MdAcUnit,
  MdKitchen,
  MdInventory2,
  MdBathroom,
  MdHotTub,
  MdSolarPower,
  MdPower,
  MdElevator,
  MdAccessible,
  MdSmokeFree,
  MdFireExtinguisher,
  MdExitToApp,
  MdPets,
  MdMale,
  MdFemale,
  MdSchedule,
  MdHourglassEmpty,
  MdCheckCircle,
  MdLogout,
  MdGavel,
  MdBlock,
  MdCancel,
  MdMeetingRoom,
  MdPayments,
  MdVerifiedUser,
  MdEditNote,
  MdPauseCircle,
  MdEventBusy,
  MdLooksOne,
  MdToday,
  MdDateRange,
  MdCalendarMonth,
  MdCalendarViewMonth,
  MdEvent,
  MdSmartphone,
  MdAccountBalance,
  MdReceiptLong,
  MdMoneyOff,
  MdSavings,
  MdUndo,
  MdTune,
  MdReply,
  MdEdit,
  MdCategory,
  MdReceipt,
  MdLogin,
  MdPersonOff,
  MdDirectionsWalk,
  MdAir,
  MdTravelExplore,
  MdFlightTakeoff,
  MdLanguage,
  MdChat,
  MdInfo,
  MdWarning,
  MdError,
} from "react-icons/md";

export const iconRegistry = {
  // Utilities
  wifi: MdWifi,
  water: MdWaterDrop,
  "water-drop": MdWaterDrop,
  electricity: MdBolt,
  bolt: MdBolt,
  "electric-bolt": MdBolt,
  gas: MdLocalGasStation,
  "gas-cylinder": MdLocalGasStation,
  trash: MdDelete,
  tv: MdTv,
  shield: MdSecurity,
  security: MdSecurity,
  broom: MdCleaningServices,
  parking: MdLocalParking,
  local_parking: MdLocalParking,
  tools: MdBuild,
  build: MdBuild,

  // Unit Types
  bed: MdBed,
  apartment: MdApartment,
  king_bed: MdKingBed,
  weekend: MdWeekend,
  villa: MdVilla,
  home: MdHome,
  home_work: MdHomeWork,
  holiday_village: MdHolidayVillage,
  domain: MdDomain,
  stairs: MdStairs,

  single_bed: MdSingleBed,
  bedroom_parent: MdBedroomParent,
  bunk_bed: MdBed,

  hotel: MdHotel,
  hotel_class: MdHotelClass,
  star: MdStar,
  family_restroom: MdFamilyRestroom,

  business: MdBusiness,
  corporate_fare: MdCorporateFare,
  groups: MdGroups,
  storefront: MdStorefront,
  warehouse: MdWarehouse,

  // Features
  lan: MdLan,
  person_shield: MdSecurity,
  intercom: MdChat,
  gate: MdSecurity,

  balcony: MdBalcony,
  deck: MdDeck,
  ac_unit: MdAcUnit,
  heat: MdAcUnit,

  kitchen: MdKitchen,
  countertops: MdKitchen,
  inventory_2: MdInventory2,

  bathroom: MdBathroom,
  hot_tub: MdHotTub,

  solar_power: MdSolarPower,
  power: MdPower,

  elevator: MdElevator,
  accessible: MdAccessible,

  smoke_free: MdSmokeFree,
  fire_extinguisher: MdFireExtinguisher,
  exit_to_app: MdExitToApp,

  pets: MdPets,

  // Gender
  male: MdMale,
  female: MdFemale,
  person: MdPerson,

  // Statuses
  schedule: MdSchedule,
  hourglass_empty: MdHourglassEmpty,
  check_circle: MdCheckCircle,
  logout: MdLogout,
  gavel: MdGavel,
  block: MdBlock,
  cancel: MdCancel,

  meeting_room: MdMeetingRoom,

  // Finance
  payments: MdPayments,
  verified_user: MdVerifiedUser,
  account_balance: MdAccountBalance,
  smartphone: MdSmartphone,

  receipt_long: MdReceiptLong,
  money_off: MdMoneyOff,
  savings: MdSavings,
  undo: MdUndo,
  tune: MdTune,
  reply: MdReply,
  edit: MdEdit,
  receipt: MdReceipt,

  // Lease
  edit_note: MdEditNote,
  pause_circle: MdPauseCircle,
  event_busy: MdEventBusy,

  // Billing
  looks_one: MdLooksOne,
  today: MdToday,
  date_range: MdDateRange,
  calendar_month: MdCalendarMonth,
  calendar_view_month: MdCalendarViewMonth,
  event: MdEvent,

  // Transaction
  category: MdCategory,

  // Booking
  login: MdLogin,
  person_off: MdPersonOff,

  directions_walk: MdDirectionsWalk,
  air: MdAir,
  travel_explore: MdTravelExplore,
  flight_takeoff: MdFlightTakeoff,
  language: MdLanguage,
  chat: MdChat,

  // Logs
  info: MdInfo,
  warning: MdWarning,
  error: MdError,
};
